#!/usr/bin/env bash
set -euo pipefail
: "${WORK_DIR:=/tmp/book-convert}"
: "${OUTPUT_EPUB:=$WORK_DIR/book.epub}"

cd "$WORK_DIR"

python3 - <<'PY'
import re, shutil, subprocess
from pathlib import Path
from collections import Counter

IMG_DIR = Path(""$WORK_DIR"/images")
IMG_DIR.mkdir(exist_ok=True)

src = Path("hilbert.md").read_text(encoding="utf-8")

# 1. Drop Anna's Archive tail metadata (comes at the end of the last page).
idx = src.find("Document generated by Anna")
if idx != -1:
    # Find the last "<!-- page N -->" marker that appears before idx.
    markers = [m for m in re.finditer(r"<!-- page \d+ -->", src) if m.start() < idx]
    if markers:
        src = src[:markers[-1].start()]
    else:
        src = src[:idx]

# 1b. Identify image-plate pages (<50 CJK chars of real text).
page_chunks = re.split(r"<!-- page (\d+) -->", src)
image_pages = set()
for k in range(1, len(page_chunks), 2):
    pnum = int(page_chunks[k])
    pt = page_chunks[k+1] if k+1 < len(page_chunks) else ""
    cjk = sum(1 for c in pt if '一' <= c <= '鿿')
    latin = sum(1 for c in pt if c.isascii() and c.isalpha())
    # Image plate pages live in the front-matter photo section (pages 2..32
    # of this book). Beyond that, low-text pages are just end-of-chapter
    # whitespace, not photos.
    if cjk + latin < 50 and 1 < pnum <= 32:
        image_pages.add(pnum)

# Prepare resized JPEGs for image pages (keeps EPUB small)
src_pages_dir = Path(""$WORK_DIR"/pages")
for pnum in sorted(image_pages):
    src_png = src_pages_dir / f"page-{pnum:03d}.png"
    dst_jpg = IMG_DIR / f"page-{pnum:03d}.jpg"
    if src_png.exists() and not dst_jpg.exists():
        subprocess.run(
            ["magick", str(src_png), "-resize", "1000x", "-quality", "80", str(dst_jpg)],
            check=False,
        )

print(f"image plate pages: {len(image_pages)}", flush=True)

lines = src.split("\n")

is_single_cjk = lambda s: len(s) == 1 and '一' <= s <= '鿿'
is_page_num   = lambda s: bool(re.fullmatch(r"\d{1,3}", s))

# 2. Drop noise: single-CJK (side margin vertical text), bare page numbers,
#    running headers.
drop = [False] * len(lines)
for i, raw in enumerate(lines):
    s = raw.strip()
    if is_single_cjk(s) or is_page_num(s):
        drop[i] = True
    if s in {"希尔伯特", "数学世界的亚历山大"}:
        drop[i] = True
    # Orphan footnote-terminator fragments that OCR left standalone
    if s in {"译注", "——译注", "—译注", "-—译注"}:
        drop[i] = True

lines = [raw for i, raw in enumerate(lines) if not drop[i]]

# 3. Identify chapter candidates (real chapter vs TOC vs page header)
chap_title_re = re.compile(r"^第([一二三四五六七八九十廿卅百0-9]+)章[\s·•埼邨昇]*(.*)$")
chap_candidates = []
for i, raw in enumerate(lines):
    s = raw.strip()
    m = chap_title_re.match(s)
    if m and len(s) <= 20:
        chap_candidates.append((i, m.group(1), m.group(2).strip()))

def chinese_num_to_int(s):
    mapping = {"一":1,"二":2,"三":3,"四":4,"五":5,"六":6,"七":7,"八":8,"九":9,"十":10}
    if s.isdigit():
        return int(s)
    n = 0
    if "十" in s:
        parts = s.split("十")
        left = 1 if parts[0] == "" else mapping.get(parts[0], 0)
        right = mapping.get(parts[1], 0) if len(parts) > 1 and parts[1] else 0
        n = left * 10 + right
    else:
        n = mapping.get(s, 0)
    return n

toc_titles = {
    1: "青年时代", 2: "良师·益友", 3: "哲学博士", 4: "巴黎", 5: "果尔丹问题",
    6: "转变", 7: "只谈数域", 8: "桌子、椅子、啤酒杯", 9: "问题", 10: "数学的未来",
    11: "新世纪", 12: "第二个青春", 13: "热情洋溢的科学生活", 14: "空间、时间和数",
    15: "朋友和学生", 16: "物理学", 17: "战争", 18: "数学基础", 19: "新秩序",
    20: "无限", 21: "借来的时间", 22: "逻辑和认识自然", 23: "云散", 24: "晚年",
    25: "终音",
}

real_chapters = {}
seen_ints = set()
for k, (li, num, title) in enumerate(chap_candidates):
    n_int = chinese_num_to_int(num)
    # Valid chapter range for this book is 1..25
    if n_int < 1 or n_int > 25:
        continue
    # Reject garbled number strings (e.g. "一一十五" parses to 5 but is noise).
    # A canonical Chinese number for 1..25 has at most 3 chars (e.g. "二十五").
    if len(num) > 3 and not num.isdigit():
        continue
    if n_int in seen_ints:
        continue
    is_toc = False
    for j in range(k + 1, len(chap_candidates)):
        nl, nnum, _ = chap_candidates[j]
        nnum_int = chinese_num_to_int(nnum)
        if nnum_int < 1 or nnum_int > 25 or (len(nnum) > 3 and not nnum.isdigit()):
            continue
        between = sum(1 for ln in lines[li+1:nl] if ln.strip())
        if between > 20:
            break
        if nnum_int != n_int:
            is_toc = True
            break
    if is_toc:
        continue
    seen_ints.add(n_int)
    actual_title = toc_titles.get(n_int, "") or title
    real_chapters[li] = (num, actual_title)

print(f"detected {len(real_chapters)} chapters", flush=True)

# 4. Chapter-title absorption
consumed_title_lines = set()
for li, (num, title) in real_chapters.items():
    consumed_title_lines.add(li)
    j = li + 1
    while j < min(li + 10, len(lines)):
        t = lines[j].strip()
        if not t or t.startswith("<!--"):
            j += 1
            continue
        if len(t) > 15 or (t and t[-1] in "。！？"):
            break
        consumed_title_lines.add(j)
        j += 1

chap_candidate_lines = {li for li, _, _ in chap_candidates}

# 5. First pass: assemble body blocks (paragraphs) and footnote blocks.
# A footnote block: consecutive paragraph(s) starting with `*` (common in
# Chinese scanned books; translator notes and explanations).
# A paragraph is a run of non-blank lines joined together, terminated by
# sentence-ending punctuation OR by a strong break (chapter start, blank
# line before footnote start, page comment).
# We output placeholder tokens {{FN:n}} for footnotes, collecting the
# bodies to emit as pandoc footnote definitions at the end of the file.

out_blocks = []   # each element is either a str paragraph, a ("CHAPTER", num, title) tuple, or a str markdown line
footnotes = []    # list of footnote body strings

def add_footnote(body: str) -> str:
    footnotes.append(body.strip())
    return f"[^{len(footnotes)}]"

# Walk
buf = []           # accumulating main-text paragraph chunks
fn_buf = []        # accumulating current footnote body chunks
in_fn = False

def flush_main():
    if buf:
        out_blocks.append("".join(buf))
        buf.clear()

def flush_fn():
    global in_fn
    if fn_buf:
        body = "".join(fn_buf)
        body = re.sub(r"^\*+\s*", "", body).strip()
        body = re.sub(r"\s*[。.]?\s*—+\s*译\s*注\s*[。.]?\s*$", "", body).strip()
        body = re.sub(r"\s*译\s*注\s*[。.]?\s*$", "", body).strip()
        body = re.sub(r"[。.]{2,}$", "。", body).strip()

        marker = add_footnote(body)

        # Preferred: replace an unclaimed inline `*` in a recent paragraph —
        # this puts the marker next to the word it actually annotates.
        # The inline `*` pattern: `*` with alphanumeric/CJK on both sides (not
        # a footnote-body `*` at line start, not a standalone math operator).
        # An inline footnote marker: `*` with a content char before AND any
        # non-whitespace char after (CJK, Latin, or punctuation).
        inline_star_re = re.compile(r"(?<=[一-鿿A-Za-z0-9)\)])\*(?=\S)")
        attached = False
        for k in range(len(out_blocks) - 1, max(0, len(out_blocks) - 6) - 1, -1):
            b = out_blocks[k]
            if not isinstance(b, str) or b.startswith(("#", ">")):
                continue
            new_b, n_sub = inline_star_re.subn(marker, b, count=1)
            if n_sub:
                out_blocks[k] = new_b
                attached = True
                break

        # Fallback: append at end of the most recent long body paragraph.
        if not attached:
            for k in range(len(out_blocks) - 1, -1, -1):
                b = out_blocks[k]
                if isinstance(b, tuple):
                    continue
                if not isinstance(b, str):
                    continue
                if b.startswith(("#", "*", ">")):
                    continue
                if len(b) < 20:
                    continue
                out_blocks[k] = b + marker
                break

        fn_buf.clear()
    in_fn = False

# Build a map: for each non-image line, which page does it belong to?
# We use this to skip OCR text on image-plate pages (the image itself replaces
# it).
line_page = [0] * len(lines)
cur_page = 0
for i, raw in enumerate(lines):
    s = raw.strip()
    pm = re.match(r"<!-- page (\d+) -->", s) if s.startswith("<!--") else None
    if pm:
        cur_page = int(pm.group(1))
    line_page[i] = cur_page

for i, raw in enumerate(lines):
    s = raw.strip()

    # Skip the book title + author line that the OCR script wrote at top
    if s.startswith("# 希尔伯特"):
        continue
    if s == "*Constance Reid 著；袁向东 李文林 译*":
        continue

    # Real chapter heading
    if i in real_chapters:
        flush_fn()
        flush_main()
        num, title = real_chapters[i]
        out_blocks.append(("CHAPTER", num, title))
        continue

    # Page marker: flush buffers, emit image if this is an image-plate page.
    # MUST run before the image-page text-drop check below.
    if s.startswith("<!--"):
        flush_fn()
        flush_main()
        pm = re.match(r"<!-- page (\d+) -->", s)
        if pm:
            pnum = int(pm.group(1))
            if pnum in image_pages:
                img_path = IMG_DIR / f"page-{pnum:03d}.jpg"
                if img_path.exists():
                    out_blocks.append(f"![](images/page-{pnum:03d}.jpg)")
        continue

    # Drop TOC/page-header chapter markers
    if i in chap_candidate_lines and i not in real_chapters:
        continue

    # Drop all OCR text from image-plate pages — the image itself replaces it
    if line_page[i] in image_pages:
        continue

    # Skip chapter-title absorption lines
    if i in consumed_title_lines:
        continue

    if not s:
        continue

    # Detect footnote start: line begins with `*` followed by non-digit
    # (to avoid mistaking numbered lists like `*1.` for footnotes — though
    # in context, those ARE the 23 problems list so should stay as body)
    if s.startswith("*") and not re.match(r"^\*\s*\d+[.、]", s):
        # Start or continue footnote
        if not in_fn:
            # New footnote — flush any existing main buffer first
            flush_main()
            in_fn = True
        fn_buf.append(s)
        # Terminate when we see 译注 marker
        if re.search(r"译\s*注\s*[。.]?\s*$", s):
            flush_fn()
        continue

    # If we're in a footnote, keep accumulating until we see the "译注"
    # translator-note terminator OR a page break (handled above). Do NOT
    # flush on bare 。 — footnote bodies often contain multiple sentences.
    if in_fn:
        fn_buf.append(s)
        if re.search(r"译\s*注", s):
            flush_fn()
        continue

    # Main text: accumulate into buf
    buf.append(s)
    # Only flush on real sentence terminators. Quotation marks alone don't
    # end a sentence in Chinese — they may close an embedded foreign word
    # ("bequem") mid-sentence. Require a preceding 。！？ within the line.
    if s[-1] in "。！？.?!":
        flush_main()
    elif s[-1] in "”’】》)":
        # Closing quote/bracket — only terminate if it follows a real
        # sentence terminator (e.g. …。")
        if len(s) >= 2 and s[-2] in "。！？.?!":
            flush_main()

flush_fn()
flush_main()

# 6. Second pass: conservative join. Only merge when prev is clearly
# mid-sentence AND both paragraphs look like regular prose (long enough,
# Chinese chars). Avoid gluing together captions, headings, list items,
# short labels, etc.
joined = []
for block in out_blocks:
    if isinstance(block, tuple):
        joined.append(block)
        continue
    s = block
    if not joined or not isinstance(joined[-1], str):
        joined.append(s)
        continue
    prev = joined[-1]
    # Don't join anything to headings / footnote-like / short blocks /
    # image embeds.
    if prev.startswith(("#", "*", ">", "!")) or s.startswith(("#", "*", ">", "!")):
        joined.append(s)
        continue
    # Only join when prev clearly ends mid-sentence (no real terminator).
    if prev[-1] in "。！？.?!”」’】》）)":
        joined.append(s)
        continue
    # If prev is very short (< 20 chars), it's likely a caption/label/heading
    # and shouldn't absorb the next block.
    if len(prev) < 20:
        joined.append(s)
        continue
    # Don't merge if next starts with a dialogue/quotation opener or heading cue
    if s[0] in "“「『（(《【·●•　—第":
        joined.append(s)
        continue
    # Merge — prev is mid-sentence, next is a plausible continuation (any length)
    joined[-1] = prev + s

# 7. Emit final markdown
out_lines = ["# 希尔伯特 — 数学世界的亚历山大", "", "*Constance Reid 著；袁向东 李文林 译*", ""]
for block in joined:
    if isinstance(block, tuple):
        _, num, title = block
        out_lines.append(f"## 第{num}章 {title}".strip())
        out_lines.append("")
    else:
        out_lines.append(block)
        out_lines.append("")

# Emit footnote definitions at end (pandoc picks them up anywhere)
if footnotes:
    out_lines.append("")
    for i, body in enumerate(footnotes, 1):
        # Clean up trailing ——译注 marker if present (since it's now redundant
        # in a footnote context — but keep it, it's informative)
        body = body.replace("\n", " ").strip()
        out_lines.append(f"[^{i}]: {body}")
        out_lines.append("")

final = []
prev_blank = False
for line in out_lines:
    if line == "":
        if not prev_blank:
            final.append(line)
        prev_blank = True
    else:
        final.append(line)
        prev_blank = False

result = "\n".join(final)

# Post-processing: insert headings for back-matter sections.
# 1. "后记" as a standalone short line OR at the start of a paragraph beginning
#    with quotation marks about Hilbert.
# 2. Translator's note section (starts with "《希尔伯特》中文版由...").
# 3. A final "译者1999年12月" signature line.
result = re.sub(
    r"(\n\s*)后记\s*(?=“大卫·希尔伯特是他那个时代真正伟大)",
    r"\1## 后记\n\n",
    result,
)
result = re.sub(
    r"(\n\s*)(?=《希尔伯特》中文版由上海科学技术出版社)",
    r"\1## 译者后记\n\n",
    result,
)

# Front-matter section headings: several titles are glued to the start of
# their paragraphs. Split them into proper headings.
result = re.sub(
    r"(内容简介)[:：]\s*",
    r"\n\n## 内容简介\n\n",
    result,
)
result = re.sub(
    r"(?m)^(作者简介)[:：]\s*",
    r"## 作者简介\n\n",
    result,
)
result = re.sub(
    r"(?m)^出版说明(?=自中西文明)",
    "## 出版说明\n\n",
    result,
)
result = re.sub(
    r"(?m)^重读《希尔伯特》之遐想(?=到1965年|\s|$)",
    "## 重读《希尔伯特》之遐想\n\n",
    result,
)

# Drop the garbled TOC entries that leaked into body text.
# Line 1: "目录重读《希尔伯特》之遐想"
# Line 2: "日第十章数学的未来…85改学世界的亚历山大第十二章第十三章..."
result = re.sub(r"(?m)^目录重读《希尔伯特》之遐想\s*$", "", result)
result = re.sub(
    r"(?m)^日?第十章数学的未来.*?译后记\d+\s*$",
    "",
    result,
)

Path("hilbert_clean.md").write_text(result, encoding="utf-8")
print(f"output: {len(final)} lines, {len(footnotes)} footnotes")
PY

pandoc hilbert_clean.md \
    -o "$OUTPUT_EPUB" \
    --from=markdown-tex_math_dollars-raw_tex \
    --toc --toc-depth=2 --split-level=2 \
    --resource-path="$WORK_DIR" \
    --metadata title="希尔伯特 — 数学世界的亚历山大" \
    --metadata author="Constance Reid" \
    --metadata lang=zh-CN

ls -lh "$OUTPUT_EPUB"
