"""Clean assembled markdown and build EPUB via pandoc.

Reads a `book_config.json` that describes this specific book's structure
(chapter titles, running headers, front/back-matter sections, image-plate
range). This replaces the book-specific regex logic that used to live in
this script as hardcoded strings for the Hilbert biography.

Environment:
    WORK_DIR        directory with md_parts/, pages/, and hilbert.md
    OUTPUT_EPUB     path to write the final .epub
    BOOK_CONFIG     path to book_config.json (default: $WORK_DIR/book_config.json)
"""
from __future__ import annotations

import json
import os
import re
import subprocess
from collections import Counter
from pathlib import Path

WORK_DIR = Path(os.environ.get("WORK_DIR", "/tmp/book-convert"))
OUTPUT_EPUB = Path(os.environ.get("OUTPUT_EPUB", str(WORK_DIR / "book.epub")))
BOOK_CONFIG = Path(os.environ.get("BOOK_CONFIG", str(WORK_DIR / "book_config.json")))

IMG_DIR = WORK_DIR / "images"
IMG_DIR.mkdir(exist_ok=True)


def load_config() -> dict:
    if not BOOK_CONFIG.exists():
        raise SystemExit(
            f"book_config.json not found at {BOOK_CONFIG}. "
            "Generate one with analyze_book.py or hand-author it."
        )
    return json.loads(BOOK_CONFIG.read_text(encoding="utf-8"))


def chinese_num_to_int(s: str) -> int:
    mapping = {"一":1,"二":2,"三":3,"四":4,"五":5,"六":6,"七":7,"八":8,"九":9,"十":10}
    if s.isdigit():
        return int(s)
    if "十" in s:
        parts = s.split("十")
        left = 1 if parts[0] == "" else mapping.get(parts[0], 0)
        right = mapping.get(parts[1], 0) if len(parts) > 1 and parts[1] else 0
        return left * 10 + right
    return mapping.get(s, 0)


def strip_trailer(src: str, markers: list[str]) -> str:
    """Drop trailing metadata from PDF provenance tools (Anna's Archive, etc.)."""
    for marker in markers:
        idx = src.find(marker)
        if idx == -1:
            continue
        page_markers = [m for m in re.finditer(r"<!-- page \d+ -->", src) if m.start() < idx]
        if page_markers:
            src = src[:page_markers[-1].start()]
        else:
            src = src[:idx]
    return src


def build_clean_md(cfg: dict) -> str:
    source_md = WORK_DIR / cfg.get("source_md", "hilbert.md")
    src = source_md.read_text(encoding="utf-8")

    # 1. Trim trailing metadata (Anna's Archive, OCR-tool banners, etc.)
    src = strip_trailer(src, cfg.get("trailer_markers", ["Document generated by Anna"]))

    # 2. Identify image-plate pages by text density within a configured range.
    plate_range = cfg.get("image_plate_range")  # e.g. [2, 32] or None
    page_chunks = re.split(r"<!-- page (\d+) -->", src)
    image_pages: set[int] = set()
    if plate_range:
        lo, hi = plate_range
        for k in range(1, len(page_chunks), 2):
            pnum = int(page_chunks[k])
            pt = page_chunks[k + 1] if k + 1 < len(page_chunks) else ""
            cjk = sum(1 for c in pt if "\u4e00" <= c <= "\u9fff")
            latin = sum(1 for c in pt if c.isascii() and c.isalpha())
            if cjk + latin < cfg.get("image_plate_text_threshold", 50) and lo <= pnum <= hi:
                image_pages.add(pnum)

    # Prepare resized JPEGs for image pages (keeps EPUB small).
    src_pages_dir = WORK_DIR / "pages"
    for pnum in sorted(image_pages):
        src_png = src_pages_dir / f"page-{pnum:03d}.png"
        dst_jpg = IMG_DIR / f"page-{pnum:03d}.jpg"
        if src_png.exists() and not dst_jpg.exists():
            subprocess.run(
                ["magick", str(src_png), "-resize", "1000x", "-quality", "80", str(dst_jpg)],
                check=False,
            )
    print(f"image plate pages: {len(image_pages)}", flush=True)

    lines = src.split("\n")

    # 3. Drop OCR noise lines: single CJK chars (side-margin vertical text),
    #    bare page numbers, configured running headers, orphan footnote
    #    terminators.
    running_headers = set(cfg.get("running_headers", []))
    orphan_markers = set(cfg.get("orphan_fragments", ["译注", "——译注", "—译注", "-—译注"]))
    is_single_cjk = lambda s: len(s) == 1 and "\u4e00" <= s <= "\u9fff"
    is_page_num = lambda s: bool(re.fullmatch(r"\d{1,3}", s))

    drop = [False] * len(lines)
    for i, raw in enumerate(lines):
        s = raw.strip()
        if is_single_cjk(s) or is_page_num(s):
            drop[i] = True
        elif s in running_headers or s in orphan_markers:
            drop[i] = True
    lines = [raw for i, raw in enumerate(lines) if not drop[i]]

    # 4. Detect real chapter starts.
    chap_pattern = cfg.get("chapter_pattern", r"^第([一二三四五六七八九十廿卅百0-9]+)章[\s·•]*(.*)$")
    chap_re = re.compile(chap_pattern)
    chapter_count = cfg.get("chapter_count", 99)
    toc_titles_raw = cfg.get("chapter_titles", {})
    toc_titles = {int(k): v for k, v in toc_titles_raw.items()}

    chap_candidates: list[tuple[int, str, str]] = []
    for i, raw in enumerate(lines):
        s = raw.strip()
        m = chap_re.match(s)
        if m and len(s) <= 20:
            num = m.group(1)
            title = m.group(2).strip() if m.lastindex and m.lastindex >= 2 else ""
            chap_candidates.append((i, num, title))

    real_chapters: dict[int, tuple[str, str]] = {}
    seen_ints: set[int] = set()
    for k, (li, num, title) in enumerate(chap_candidates):
        n_int = chinese_num_to_int(num)
        if n_int < 1 or n_int > chapter_count:
            continue
        if len(num) > 3 and not num.isdigit():
            # Garbled number string — reject
            continue
        if n_int in seen_ints:
            continue
        # TOC vs body: if another DIFFERENT-number chapter candidate appears
        # within 20 non-blank lines, this is a TOC entry.
        is_toc = False
        for j in range(k + 1, len(chap_candidates)):
            nl, nnum, _ = chap_candidates[j]
            nnum_int = chinese_num_to_int(nnum)
            if nnum_int < 1 or nnum_int > chapter_count:
                continue
            between = sum(1 for ln in lines[li + 1 : nl] if ln.strip())
            if between > 20:
                break
            if nnum_int != n_int:
                is_toc = True
                break
        if is_toc:
            continue
        seen_ints.add(n_int)
        real_chapters[li] = (num, toc_titles.get(n_int, "") or title)

    print(f"detected {len(real_chapters)} chapters", flush=True)

    # 5. Absorb lines that restate the chapter title right after the marker.
    consumed_title_lines: set[int] = set()
    for li, (num, title) in real_chapters.items():
        consumed_title_lines.add(li)
        j = li + 1
        while j < min(li + 10, len(lines)):
            t = lines[j].strip()
            if not t or t.startswith("<!--"):
                j += 1
                continue
            if len(t) > 15 or (t and t[-1] in "。！？"):
                break
            consumed_title_lines.add(j)
            j += 1

    chap_candidate_lines = {li for li, _, _ in chap_candidates}

    # Page number for each line (for image-plate text suppression).
    line_page = [0] * len(lines)
    cur_page = 0
    for i, raw in enumerate(lines):
        s = raw.strip()
        if s.startswith("<!--"):
            pm = re.match(r"<!-- page (\d+) -->", s)
            if pm:
                cur_page = int(pm.group(1))
        line_page[i] = cur_page

    # 6. First pass: build paragraphs and footnotes.
    skip_lines = set(cfg.get("skip_exact_lines", []))
    book_title_heading_prefix = cfg.get("book_title_heading_prefix", "")

    out_blocks: list = []
    footnotes: list[str] = []
    buf: list[str] = []
    fn_buf: list[str] = []
    in_fn = False

    def add_footnote(body: str) -> str:
        footnotes.append(body.strip())
        return f"[^{len(footnotes)}]"

    def flush_main() -> None:
        if buf:
            out_blocks.append("".join(buf))
            buf.clear()

    inline_star_re = re.compile(r"(?<=[一-鿿A-Za-z0-9)\)])\*(?=\S)")
    footnote_terminator_re = re.compile(r"译\s*注")

    def flush_fn() -> None:
        nonlocal in_fn
        if fn_buf:
            body = "".join(fn_buf)
            body = re.sub(r"^\*+\s*", "", body).strip()
            body = re.sub(r"\s*[。.]?\s*—+\s*译\s*注\s*[。.]?\s*$", "", body).strip()
            body = re.sub(r"\s*译\s*注\s*[。.]?\s*$", "", body).strip()
            body = re.sub(r"[。.]{2,}$", "。", body).strip()

            marker = add_footnote(body)
            attached = False
            for k in range(len(out_blocks) - 1, max(0, len(out_blocks) - 6) - 1, -1):
                b = out_blocks[k]
                if not isinstance(b, str) or b.startswith(("#", ">")):
                    continue
                new_b, n_sub = inline_star_re.subn(marker, b, count=1)
                if n_sub:
                    out_blocks[k] = new_b
                    attached = True
                    break
            if not attached:
                for k in range(len(out_blocks) - 1, -1, -1):
                    b = out_blocks[k]
                    if isinstance(b, tuple):
                        continue
                    if not isinstance(b, str):
                        continue
                    if b.startswith(("#", "*", ">")):
                        continue
                    if len(b) < 20:
                        continue
                    out_blocks[k] = b + marker
                    break
            fn_buf.clear()
        in_fn = False

    for i, raw in enumerate(lines):
        s = raw.strip()
        if s in skip_lines:
            continue
        if book_title_heading_prefix and s.startswith(book_title_heading_prefix):
            continue

        if i in real_chapters:
            flush_fn()
            flush_main()
            num, title = real_chapters[i]
            out_blocks.append(("CHAPTER", num, title))
            continue

        if s.startswith("<!--"):
            flush_fn()
            flush_main()
            pm = re.match(r"<!-- page (\d+) -->", s)
            if pm:
                pnum = int(pm.group(1))
                if pnum in image_pages:
                    img_path = IMG_DIR / f"page-{pnum:03d}.jpg"
                    if img_path.exists():
                        out_blocks.append(f"![](images/page-{pnum:03d}.jpg)")
            continue

        if i in chap_candidate_lines and i not in real_chapters:
            continue
        if line_page[i] in image_pages:
            continue
        if i in consumed_title_lines:
            continue
        if not s:
            continue

        # Footnote start: `*` prefix, not a numbered-list-like `*1.`
        if s.startswith("*") and not re.match(r"^\*\s*\d+[.、]", s):
            if not in_fn:
                flush_main()
                in_fn = True
            fn_buf.append(s)
            if footnote_terminator_re.search(s):
                flush_fn()
            continue

        if in_fn:
            fn_buf.append(s)
            if footnote_terminator_re.search(s):
                flush_fn()
            continue

        buf.append(s)
        if s[-1] in "。！？.?!":
            flush_main()
        elif s[-1] in "”’】》)":
            if len(s) >= 2 and s[-2] in "。！？.?!":
                flush_main()

    flush_fn()
    flush_main()

    # 7. Conservative second pass: join paragraphs split mid-sentence.
    joined: list = []
    for block in out_blocks:
        if isinstance(block, tuple):
            joined.append(block)
            continue
        s = block
        if not joined or not isinstance(joined[-1], str):
            joined.append(s)
            continue
        prev = joined[-1]
        if prev.startswith(("#", "*", ">", "!")) or s.startswith(("#", "*", ">", "!")):
            joined.append(s)
            continue
        if prev[-1] in "。！？.?!”」’】》）)":
            joined.append(s)
            continue
        if len(prev) < 20:
            joined.append(s)
            continue
        if s[0] in "“「『（(《【·●•　—第":
            joined.append(s)
            continue
        joined[-1] = prev + s

    # 8. Emit final markdown
    out_lines: list[str] = []
    title = cfg.get("title", "")
    author_line = cfg.get("author_line", "")
    if title:
        out_lines += [f"# {title}", ""]
    if author_line:
        out_lines += [f"*{author_line}*", ""]

    for block in joined:
        if isinstance(block, tuple):
            _, num, chap_title = block
            heading = f"## 第{num}章 {chap_title}".strip()
            out_lines += [heading, ""]
        else:
            out_lines += [block, ""]

    if footnotes:
        out_lines.append("")
        for i, body in enumerate(footnotes, 1):
            body = body.replace("\n", " ").strip()
            out_lines += [f"[^{i}]: {body}", ""]

    # Dedupe consecutive blank lines
    final: list[str] = []
    prev_blank = False
    for line in out_lines:
        if line == "":
            if not prev_blank:
                final.append(line)
            prev_blank = True
        else:
            final.append(line)
            prev_blank = False

    result = "\n".join(final)

    # 9. Post-processing: promote front/back-matter sections to headings.
    for rule in cfg.get("heading_promotions", []):
        pattern = rule["pattern"]
        title = rule["title"]
        flags = 0
        for flag in rule.get("flags", []):
            flags |= getattr(re, flag)
        repl = rule.get("replacement")
        if repl is None:
            repl = f"\n\n## {title}\n\n"
        result = re.sub(pattern, repl, result, flags=flags)

    # 10. Drop configured trailer/junk patterns.
    for pattern in cfg.get("drop_patterns", []):
        result = re.sub(pattern, "", result, flags=re.MULTILINE)

    return result


def main() -> None:
    cfg = load_config()
    clean = build_clean_md(cfg)

    clean_md_path = WORK_DIR / cfg.get("output_md", "book_clean.md")
    clean_md_path.write_text(clean, encoding="utf-8")
    print(f"wrote {clean_md_path}", flush=True)

    pandoc_args = [
        "pandoc",
        str(clean_md_path),
        "-o",
        str(OUTPUT_EPUB),
        "--from=markdown-tex_math_dollars-raw_tex",
        "--toc",
        f"--toc-depth={cfg.get('toc_depth', 2)}",
        f"--split-level={cfg.get('split_level', 2)}",
        f"--resource-path={WORK_DIR}",
    ]
    for key in ("title", "author", "translator"):
        if key in cfg and cfg[key]:
            pandoc_args += ["--metadata", f"{key}={cfg[key]}"]
    lang = cfg.get("language", "zh-CN")
    pandoc_args += ["--metadata", f"lang={lang}"]

    subprocess.run(pandoc_args, check=True)
    print(f"wrote {OUTPUT_EPUB}", flush=True)


if __name__ == "__main__":
    main()
